# Generated by Django 4.2.18 on 2025-03-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tempmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('feedbackform', models.CharField(max_length=100)),
            ],
        ),
    ]
